### ISSUE TITLE
Screen Shot

### ISSUE THREAD

**Issue by qcdong2016** [qcdong2016/quick-x#13]
![menu](https://cloud.githubusercontent.com/assets/6292878/19440822/ef2718b2-94b5-11e6-8bf0-098207b7983e.png)
![openproject](https://cloud.githubusercontent.com/assets/6292878/19440821/ef2215c4-94b5-11e6-9ee9-8b93328ae0a9.png)

**Comment by qcdong2016** [comment]
Shader Uniform Editor,  all in lua.

![2](https://cloud.githubusercontent.com/assets/6292878/19828715/3cf22d7c-9e00-11e6-8cd7-966a24e1cf09.jpg)
![3](https://cloud.githubusercontent.com/assets/6292878/19828717/3cf89e14-9e00-11e6-9a3b-968c12f3ea5e.jpg)
![1](https://cloud.githubusercontent.com/assets/6292878/19828716/3cf686a6-9e00-11e6-8c3f-c9eeb9c2362c.jpg)

**Comment by qcdong2016** [comment]
Shader Uniform Editor. Make it in lua.
![3](https://cloud.githubusercontent.com/assets/6292878/19828770/c79e59b8-9e01-11e6-93c7-5c93479abe78.jpg)
![1](https://cloud.githubusercontent.com/assets/6292878/19828771/c7e0d6a8-9e01-11e6-8756-4bf1f3b7a423.jpg)
![2](https://cloud.githubusercontent.com/assets/6292878/19828772/c823eaec-9e01-11e6-843c-79f5e4a79058.jpg)

**Comment by yinjimmy** [comment]
![image](https://cloud.githubusercontent.com/assets/5056328/25566614/059b23b6-2e0f-11e7-91d9-462f612e244f.png)
